let MENU=[],cartItems=[],orders=[],socket=null,adminMode=false,cat='All';
const money=n=>'₹'+Number(n).toLocaleString('en-IN');
const toast=t=>{const x=document.createElement('div');x.className='toast';x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),1800)};
const cartTotal=()=>cartItems.reduce((s,x)=>s+x.price*x.qty,0);
function connect(){socket=new WebSocket((location.protocol==='https:'?'wss://':'ws://')+location.host+'/ws');socket.onopen=()=>setLive(true);socket.onclose=()=>{setLive(false);setTimeout(connect,2000)};socket.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==='orders.snapshot')orders=m.orders||[];if(m.type==='order.created'){orders.unshift(m.order);toast('🔔 New order '+m.order.id)}if(m.type==='order.updated'){const i=orders.findIndex(x=>x.id===m.order.id);if(i>=0)orders[i]=m.order;else orders.unshift(m.order)}if(adminMode)renderAdmin()};}
function setLive(v){const el=document.querySelector('.realtime');if(el){el.textContent=v?'● LIVE':'● OFFLINE';el.className='realtime '+(v?'':'offline')}}
async function init(){MENU=await fetch('/api/menu').then(r=>r.json());connect();customer()}
function customer(){adminMode=false;document.body.className='';renderCustomer()}
function renderCustomer(){const cats=['All',...new Set(MENU.map(x=>x.cat))];const items=MENU.filter(x=>cat==='All'||x.cat===cat);document.getElementById('app').innerHTML=`<main class="shell"><div class="top"><div class="brand">The Backyard Social</div><div class="row"><span class="realtime">● LIVE</span><button class="pill" onclick="admin()">Admin</button></div></div><section class="hero"><h1>Order from your table.</h1><p>Scan. Choose. Order. We’ll bring it to you.</p></section><div class="cats">${cats.map(c=>`<button class="${c===cat?'active':''}" onclick="setCat('${c}')">${c}</button>`).join('')}</div><section class="grid">${items.map(x=>`<article class="card"><div class="emoji">${x.emoji}</div><h3>${x.name}</h3><div class="muted small">${x.desc}</div><div class="row"><span class="price">${money(x.price)}</span><button class="secondary" onclick="add(${x.id})">Add</button></div></article>`).join('')}</section>${cartItems.length?`<div class="cartbar row"><div><b>${cartItems.reduce((s,x)=>s+x.qty,0)} items</b><div class="muted">${money(cartTotal())}</div></div><button class="primary" style="width:auto" onclick="cart()">View Cart</button></div>`:''}</main>`}
window.setCat=c=>{cat=c;renderCustomer()};window.add=id=>{const x=MENU.find(x=>x.id===id),f=cartItems.find(i=>i.id===id);f?f.qty++:cartItems.push({...x,qty:1});toast(x.name+' added');renderCustomer()};
function cart(){document.body.innerHTML=`<div class="modal"><div class="panel"><div class="row"><h2>Your order</h2><button class="secondary" onclick="customer()">✕</button></div>${cartItems.map(x=>`<div class="line"><div><b>${x.name}</b><div class="muted">${money(x.price)} × ${x.qty}</div></div><div><button class="secondary" onclick="change(${x.id},-1)">−</button> <button class="secondary" onclick="change(${x.id},1)">+</button></div></div>`).join('')}<div class="row" style="margin-top:16px"><b>Total</b><span class="total">${money(cartTotal())}</span></div><button class="primary" style="margin-top:14px;width:100%" onclick="checkout()">Continue</button></div></div>`}
window.change=(id,d)=>{const x=cartItems.find(x=>x.id===id);if(x)x.qty+=d;cartItems=cartItems.filter(x=>x.qty>0);cart()};
function checkout(){document.body.innerHTML=`<div class="modal"><div class="panel"><div class="row"><h2>Checkout</h2><button class="secondary" onclick="cart()">Back</button></div><div class="field"><label>Table number</label><input id="table" value="T04"></div><div class="field"><label>Name</label><input id="name" placeholder="Your name"></div><div class="field"><label>Payment</label><select id="pay"><option>UPI</option><option>Card</option><option>Cash</option></select></div><div class="card row"><span>Total</span><b>${money(cartTotal())}</b></div><button class="primary" style="margin-top:14px;width:100%" onclick="placeOrder()">Place Order</button></div></div>`}
async function placeOrder(){const r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({table:document.getElementById('table').value,name:document.getElementById('name').value||'Guest',payment:document.getElementById('pay').value,items:cartItems})});const o=await r.json();if(!r.ok)return toast(o.error||'Order failed');cartItems=[];document.body.innerHTML=`<div class="modal"><div class="panel" style="text-align:center"><div class="emoji">🎉</div><h2>Order received</h2><p class="muted">${o.id} is now in the kitchen.</p><span class="status">New</span><button class="primary" style="margin-top:20px;width:100%" onclick="customer()">Back to Menu</button></div></div>`}
function admin(){adminMode=true;document.body.className='admin';document.getElementById('app').innerHTML='<main class="shell"><div class="top"><div><div class="brand">Kitchen / Admin</div><div class="muted">The Backyard Social</div></div><div class="row"><span class="realtime">● LIVE</span><button class="pill" onclick="customer()">Customer</button></div></div><div id="adminView"></div></main>';renderAdmin()}
function renderAdmin(){if(!adminMode)return;document.getElementById('adminView').innerHTML=`<div class="tabs"><button class="secondary" onclick="renderAdmin()">Orders (${orders.length})</button><button class="secondary" onclick="menuView()">Menu</button><button class="secondary" onclick="customer()">Customer</button></div>${orders.length?orders.map(o=>`<article class="card order"><div class="row"><div><b>${o.id}</b><div class="muted small">Table ${o.table} · ${o.name} · ${o.payment}</div></div><span class="status">${o.status}</span></div><div class="items">${o.items.map(i=>`<div class="row small"><span>${i.qty} × ${i.name}</span><b>${money(i.qty*i.price)}</b></div>`).join('')}</div><div class="row"><b>${money(o.total)}</b><select onchange="updateStatus('${o.id}',this.value)">${['New','Preparing','Ready','Completed','Cancelled'].map(s=>`<option ${s===o.status?'selected':''}>${s}</option>`).join('')}</select></div></article>`).join(''):'<div class="empty">No orders yet.</div>'}`}
window.updateStatus=async(id,status)=>{await fetch('/api/orders/'+id+'/status',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})})};function menuView(){document.getElementById('adminView').innerHTML='<div class="card"><h2>Menu</h2><p class="muted">Menu editing will be backed by PostgreSQL in the next admin pass.</p></div>'}
init();
